Wpsolr integration
semi-technologies/weaviate-io pull request #167
Opened 2022-07-30 16:02 UTC by eostis

### Why:

Submission of WPSOLR as a new integration

### What's being changed:

integrations.yml and WPSOLR's logo.

### Type of change:

- [ ] Documentation updates (non-breaking change which updates documents)

### How Has This Been Tested?

Just documentation changes.

2022-07-30 16:04 UTC, eostis commented
Pull request to add WPSOLR as an integration

2022-07-31 10:07 UTC, bobvanluijt commented on _data/integrations.yml
> +  description: Power all or parts of your search with Weaviate. We've integrated all Weaviate modules, including transformers, Question & Answers, and CLIP to extend OpenSearch, Algolia, Solr, Solr C
@eostis would be good to just focus on the Weaviate integration. For the rest this looks ok.

2022-07-31 10:07 UTC, bobvanluijt requested changes
See below

2022-07-31 10:21 UTC, eostis commented
I agree with the CLA https://www.semi.technology/playbooks/misc/contributor-license-agreement.html

2022-08-01 14:43 UTC, bobvanluijt approved these changes

2022-08-01 14:43 UTC, merged

2022-08-01 15:24 UTC, eostis commented
I's live now. Thanks. 👍

2022-08-01 15:27 UTC, bobvanluijt commented
Thank you for the contrib 😊👍